apiVersion: v1
data:
    client_id: ENC[AES256_GCM,data:2j+1DVfAnX5ZGGp8C5qXuEgxHT3EeNhKwpXhsPQN/2RoQTu/QqaV9rakLjWh8gl7,iv:BKh1fPMPhUs9m9QtPdrg+hmHhAbnU7RVmHWK8eE+H3Y=,tag:gVVpSCuiG0eHq9d4rRnjLQ==,type:str]
    client_secret: ENC[AES256_GCM,data:UklQ0I6pABEEeOcE7C1ybpqOqfCC61H65H3KMLLTVMwbjcXUb/NhqvZDhvY+wzgpmAX5rjms/mo=,iv:KdIAUCsTXkMafzoXGfDSYcyzNL28zIuq9D1QFiGtwMk=,tag:jIL9xIlawI8wyoip5ZVEPw==,type:str]
kind: Secret
metadata:
    name: az-service-principal
sops:
    age:
        - recipient: age15nh307szugl4u5hp65zgy9fm2cyqd35mlnawusl768g47n420e7sdrrsge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWngyWnptMHhydnJIRlRw
            YjNXak1tWU4rYVNEQkVkbll1QVBmZkMvZEFVCnhTREJta0tCWFlEWHN5NmhGWDBU
            SzZCQWdyYjR6MGRKeEN2dVZvbHgwWWcKLS0tIHpmRUloZG5GamlVNWQvUG9rNWxk
            a29QSUZKeER5amg1YVZCVTlHOURQcDQKKU50Miy4J4cE/Zk8qSH4zJtlgxj0xoEG
            UK6f2/JvYcAHDU98DG49PkciXUZHfqjLm0/PEjL/egGI6z+PS8MY8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-14T09:28:03Z"
    mac: ENC[AES256_GCM,data:IQUjcCWF7kWAWVLjRNuAfNOGBW4P/MLVXFTP+d3RNeVDngiCqOIfnV8xee2ypf2S5vu+FZpQIjc7/VAyxmKAMNMnTGC03A+DaeJb+f+SkJyxxkZSPNsCufAJR5ASpJ1TOMsltq0q0YOp8OjDtklM0/Fe5pgeUkaj2iRDe5GMi+Q=,iv:49a+DtPCsA3Agnn7//6geWYlkifSS/L7YRdtmNPNZ6c=,tag:Yh0NiV8keWKR4qydSZ3C2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2