apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  interval: 10m

  # # ⬇️ TO MA BYĆ TUTAJ
  # dependsOn:
  #   - name: external-secrets-crds

  chart:
    spec:
      chart: external-secrets
      version: 0.18.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system

  values:
    installCRDs: false

  install:
    createNamespace: true
