apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets-repo
        namespace: external-secrets
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace