apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:OtCzEbpFxKQOmH70neN4MZMx590Gjq0/2udpT9GlBGj4NWgjUv2p/hwUkRZtjwstKXwYq/Ains0pqES/vmO1bFznRiBydJgJt/D7Kh8BQa0mQT6IjDM2PqLhyjOYxpaqXannTpDRUTZuTWUhNxlYI5pKuW/tERUOUpZBCD+ASfGWl5v5WPqJ3QcABATRNRIq0Rc+sutfDfCbCdsOI2OwWHwuPgHulkaUWzRxr+QavvE=,iv:G9Ul6RA190CwWibLrL3bl4A4iw5XGoqen5Orr3j8ko0=,tag:3+KIRv1NxpQTCbEq5AK+Pw==,type:str]
kind: Secret
metadata:
    name: fastapi
sops:
    age:
        - recipient: age15nh307szugl4u5hp65zgy9fm2cyqd35mlnawusl768g47n420e7sdrrsge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdUY1azVLN1BKMUZ2Rnp6
            bThtblBkSXpzdlFPMFQrakpxUzRkalhPQndFCmExV1dwQUpKT3kyRWNHRkhBQjlQ
            WUFRNG5yWDFSbFM4eUF0Y3pzdmtWZGMKLS0tIDE1U3NuTHRXb2JHbE8xSVUwUkla
            TCtwUUlNN1JvNXRoUDA4QUhJMUJSRFUKNSCCK/dqb4Vf+2uQ5x7mlDTySEC9hVBk
            xk8IaV5CK+WqhPBrO3o4sX7pEfOL39w07bneKbm7epWg4WD/LpgZuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T16:16:15Z"
    mac: ENC[AES256_GCM,data:S2OjxOxHhpsLRd03rscZQqDMK/lNxiU4MlD2Y0Q8SiMRaLre3ST2IIxD6vZFNMmnclwUVnpqYdy+JtEtKYJLAcST/TmbFvKGaXTsImivGk5vHA+G0LjL23IjSwvAqwVf3mPfPFSBWY/9BuFZjOK2O/nxYvzSU9a2pmDzfBhc/FU=,iv:KHa9oWTxDpwc8tkQUvWzgoBwDRCwC4dYidxt5qryeOw=,tag:NV/wkqD9RcPchFzP3NVvVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2               