apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: database
spec:
  instances: 1
  #imageName: ghcr.io/cloudnative-pg/postgresql:13.6 #download specific version, overwrites operator's default option
  storage:
    size: 1Gi