apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: az-kv-db-password
spec:
  #refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store

  target:
    name: postgresql-app #name of a secret in k8s
    creationPolicy: Merge #Owner, Merge, None
    #deletionPolicy: Retain, Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        pgpass: "postgresql-rw:5432:app:app:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://postgresql-rw.default:5432/app?password={{ .password }}&user=app"
        uri: "postgresql://app:{{ .password }}@postgresql-rw.default:5432/app"
  #map secrets from azure keyvault to kubernetes secrets
  data:
    - secretKey: password # key name of k8s secret
      remoteRef:
        key: db-password
