apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: azure-keyvault-provider
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-secrets-store-provider-azure
      sourceRef:
        kind: HelmRepository
        name: azure-keyvault-provider
        namespace: kube-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace