#tell flux what resources to look for
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1m0s
  # dependsOn:
  #   - name: infra-configs
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/nginx
  prune: true
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
#---
