apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: az-kv-grafana-password
spec:
  #refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store

  target:
    name: grafana-credentials #name of a secret in k8s
    creationPolicy: Owner #Owner, Merge, None
    #deletionPolicy: Retain, Delete
  #map secrets from azure keyvault to kubernetes secrets
  data:
    - secretKey: adminPassword # key name of k8s secret
      remoteRef:
        key: grafana-credentials
        property: adminPassword

    - secretKey: adminUser
      remoteRef:
        key: grafana-credentials
        property: adminUser

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: az-kv-discord-webhook-url
spec:
  #refreshInterval: 1h
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store

  target:
    name: discord-webhook-url #name of a secret in k8s
    creationPolicy: Owner #Owner, Merge, None
    #deletionPolicy: Retain, Delete
  #map secrets from azure keyvault to kubernetes secrets
  data:
    - secretKey: webhook-url # key name of k8s secret
      remoteRef:
        key: discord-webhook-url


