apiVersion: v1
data:
    LD_DB_PASSWORD: ENC[AES256_GCM,data:lkEZKSqxnu0Ud8WyWbfs0fqvqBVxqGVzvGJWtsYLvqlWbkzvG4qvYOZfdxDsG2bvOwpWVPldh/igYJLjA+29k4xiunBJ9OTjxnMn02qRvYFyOgD6PHPuow==,iv:wj33uskAMkAsJg0s/eFtZWmXOQwPMqIMX+7uyjscPog=,tag:G2NV8TqBCMtCCqJ3jrP0BQ==,type:str]
kind: Secret
metadata:
    name: linkding-database-secret
sops:
    age:
        - recipient: age15nh307szugl4u5hp65zgy9fm2cyqd35mlnawusl768g47n420e7sdrrsge
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZkxHenBNNkE4UUZUWHcr
            enN2cjFZQWlaL1VsdWk4bjVIckZib1M5WjNnCk9tRzFmTlB6UHIxS0hkVHNmNXN4
            cGxjVDVKRmlhWVZWVVZ0S1E5Z2RpdmsKLS0tIDZsZnQrUDR0L1hHNFRtVE1peStv
            MC80MVpmMnh5dXdXWkNGd0ticm85aTQKpuf3q+4EfA2Hipc8ReREM+DL2jLBkHm9
            FAMxxQzld715nkK3/1wqh7aog9vS8YiUstaeP2U4Zc2aHF0NmS+2cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-01T08:56:42Z"
    mac: ENC[AES256_GCM,data:KS6E36xCMlD1eAGIWU4CsrtZRKV9OBUJ/RyjlIDS4LFrRfvA3vrzOtqPvPZS3mfLkMCj+59DmY+5kKX0asP6MxUk+ap3z2dP7AImBzWugyv1QYBzU/Idqogvw8wHwruOMM/XCs75lDvegDAEMVvG3RZvTdWXncEV4o/KMO9RTWc=,iv:6Wdk93PTfuvT06EeLTryBwqfCo0WT6tdwQZucqJSU1Y=,tag:yp8Vcuy0KvIn1QUuVbWI/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2